# Generated by Django 5.0.6 on 2024-06-07 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott_recommend', '0004_rename_dislike_dislikecontents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DislikeContents',
            new_name='DislikeContent',
        ),
        migrations.RenameModel(
            old_name='LikeContents',
            new_name='LikeContent',
        ),
    ]
